name: automatic-stock-trader
workers:
- dockerfile_path: Dockerfile
  name: automatic-stock-trader
  github:
    branch: main
    deploy_on_push: true
    repo: Schentrup-Software/Automatic-Stock-Trader
