name: Run Daily Tracking

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 23 * * 1-5'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter TestCategory=Large
      continue-on-error: true
      env:
        ALPACA_APP_ID: ${{ secrets.ALPACA_APP_ID }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        STOCK_LIST: "GE, XPEV, F, PLTR, BAC, NOK, ACB, PFE, FSR, VALE, BABA, WFC, XOM, T, PBR, ABEV, M, NCLH, PCG, MRO, AMC, DIS, DAL, FCX, BA, ET, BSX, C, SNAP, OXY, VRT, AUY, VIPS, SWN, UBER, MGM, GM, VER, JWN, NLY, LU, KMI, AMWL, COTY, TME"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
          token: ${{ secrets.PAT }}
          commit-message: Update tracking file
          title: Update tracking file
          body: |
            - Update tracking file

            Auto-generated by [create-pull-request][1]
          branch: update-tracking
