name: Run Large Tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 23 * * 1-5'

jobs:
  run-large-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: | 
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/googlecreds.json
        echo $GOOGLE_APPLICATION_CREDENTIALS_FILE > $GOOGLE_APPLICATION_CREDENTIALS
        dotnet test --no-restore --verbosity normal --filter TestCategory=Large
      continue-on-error: true
      env:
        ALPACA_APP_ID: ${{ secrets.ALPACA_APP_ID }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        STOCK_LIST: "GE"
        GOOGLE_APPLICATION_CREDENTIALS_FILE: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_FILE }}
